### ISSUE TITLE
Duplicated fetch_json function

### ISSUE THREAD

**Issue by adrianlzt** [Telefonica/vaultier-cli#26]
``fetch_json`` is duplicated in ``client.py`` and ``auth.py``

**Comment by ogarcia** [comment]
Not is same function.

The function has the same name cause both do _similar_ work, but `fetch_json` in `auth.py` only do simple request to obtain token and `fetch_json` in `client.py` is more complete and preconfigures the token.

**Comment by adrianlzt** [comment]
OK
